services:
  drawio:
    image: jgraph/drawio:latest
    ports: ["8080:8080"]
  auto-draw-io:
    build:
      context: .
      args:
        - EMBED_DRAWIO_BASE_URL=http://localhost:8080
    ports: ["3000:3000"]
    env_file: .env
    depends_on: [drawio]
